//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assetto.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntries
    {
        public int Id { get; set; }
        public string MachineName { get; set; }
        public int Severity { get; set; }
        public string Message { get; set; }
    }
}
